### PR TITLE
IKJRaware and other Improvements

### PR DESCRIPTION
**Pull request by meirumeiru**
added the IKJRaware interface (as discussed with you)
Additionally I "fixed" the behaviour of KJR when it finds parts that shoud be ignored. In this case the way of determining how many joints should be created and between which parts is insufficient. This results in very unstable ships as soon as you add one or more excluded parts to a ship.

### CODE REVIEW

**Comment by duncanj** [comment]
Is there a build of this version around? Interested in trying it with 1.4.1 since I'm getting a lot of wobbles with parts joined by docking ports at launch.

**Comment by ferram4** [comment]
I'm going to merge this, but remove the new version files.  Those are only going to cause issues in the long run.

**Comment by ferram4** [comment]
Sorry, I thought that this was a much simpler change than it actually was.  THe huge mess that it includes with multiple projects and version files and what-not is unnecessary and I had to revert it.  Come back with a clean version of the changes, just those changes and no shenanigans and I'll merge it, but until then, no, sorry.

**Comment by meirumeiru** [comment]
that's part of the build system... together with one batch file (that I wanted to check in too) you can build a version of the project for multiple KSP versions with just one click...
the result is multiple GameData folders... then zip it and that's the release process...
... and supporting not only one version of KSP would be a bit more user friendly

**Comment by ferram4** [comment]
Which is frankly unnecessary.  Old versions of KSP can still use the older versions of KJR, but there is no reason to continue support for those versions.  No one is developing for KSP 1.2.2 anymore, since even Realism Overhaul has moved on to 1.3.1.  The last KJR release for 1.3.1 would have included this, and then all the remaining work would have gone towards 1.4.x.

Besides that, the entire build system completely broke my build system and required me dumping my entire working directory and rebuilding it from the repo.

If you insist that that system be included with this PR, then I'm afraid that I must reject everything since it makes the development process more difficult on my end.

**Comment by meirumeiru** [comment]
No, for me it's ok, I could create a special version and deleting the files you don't want
I can also convert everything to spaces instead of tabs... but I have to tell you that I did modify a lot. You have to decide if you like it or not.
But since the old KJR doesn't work together with IR and it's not possible to play without KJR (alltough, autostrut is not that bad), I need to find a solution... and if there is none, I could keep supporting my fork and allow others to use this version for configs with IR.

**Comment by meirumeiru** [comment]
I modified the project... added support for auto strut like dynamic behaviour and removed support for 1.2.2 plus converted the files (spaces instead of tabs). Support for 1.3.1 is still needed, because this version of KJR is so much different from 3.3.x that it must be ported back to this KSP. And there is no other way than to build 2 project files except for manually inserting conditions into it (because of the references).
I could do a new pull request, but ... you decide...

**Pull request merged**
