### PR TITLE
new try

### PR DESCRIPTION
**Pull request by meirumeiru**
maybe you like this one better... I removed some files that could disturb the building process when downloaded to different machines and cleaned the structure a little bit... and I fixed some files plus added additional features that were missing... and I removed the added IKJRaware and replaced it with an interface already in KSP

### CODE REVIEW

**Comment by linuxgurugamer** [comment]
You should NEVER include files that change the build environment.  This includes the sln files, the csproj files and anything else which isn't code.

If the build process must be changed (ie:  adding a new reference), include that in the notes. 

Including those project files in a PR to someone else's project is rude and unproductive.

This isn't my project, but it's been done to me many times, and I saw this while looking into the current state of KJR

**Comment by linuxgurugamer** [comment]
I would add that you also shouldn't change the .version file.

**Comment by linuxgurugamer** [comment]
I was looking at your code (again), and what struck me was that you changed the license text at the top by deleting the copyright info.

That is extremely bad.  Added a line listing yourself as a contributer or developer is fine, but removing the copyright line is not only rude, but may also be illegal under the GPL

**Comment by meirumeiru** [comment]
.

**Pull request closed without merging**
